-- =====================================================
-- 037: Per-stage / Per-series / Tournament Team Stats (Extended)
-- compute-tournament-stats 실행 시 자동 집계
-- =====================================================

-- Extend tournament_team_stats with player-aggregated columns
ALTER TABLE tournament_team_stats
  ADD COLUMN IF NOT EXISTS kills                 INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS assists               INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS knocks                INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS headshot_kills        INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS damage                NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS survival_time         NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deaths                INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS longest_kill          NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS knock_damage_sum      NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagement_dist_sum   NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagement_dist_count INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS first_blood_kills     INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS first_blood_knocks    INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS grenades_thrown       INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS smokes_thrown         INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flashbangs_thrown     INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS molotovs_thrown       INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS grenade_damage        NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS molotov_damage        NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS grenade_hit_events    INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS damage_taken          NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS blue_zone_damage      NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS heals_used            INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS boosts_used           INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_heal_amount     NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revives               INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS blue_zone_time        INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS walk_distance         NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ride_distance         NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS swim_distance         NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vehicle_time          INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revives_given         INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS assist_damage         NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS trade_kills           INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tradeable_deaths      INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS zone_edge_samples     INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS zone_total_samples    INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS zone_outside_samples  INT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS zone_dist_sum         NUMERIC NOT NULL DEFAULT 0;

-- ── stage_team_stats ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stage_team_stats (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stage_id               UUID NOT NULL REFERENCES stages(id) ON DELETE CASCADE,
  team_id                UUID REFERENCES teams(id) ON DELETE SET NULL,
  team_name              TEXT NOT NULL,
  logo_url               TEXT,
  games                  INT     NOT NULL DEFAULT 0,
  wwcd                   INT     NOT NULL DEFAULT 0,
  kills                  INT     NOT NULL DEFAULT 0,
  assists                INT     NOT NULL DEFAULT 0,
  knocks                 INT     NOT NULL DEFAULT 0,
  headshot_kills         INT     NOT NULL DEFAULT 0,
  damage                 NUMERIC NOT NULL DEFAULT 0,
  survival_time          NUMERIC NOT NULL DEFAULT 0,
  deaths                 INT     NOT NULL DEFAULT 0,
  longest_kill           NUMERIC NOT NULL DEFAULT 0,
  knock_damage_sum       NUMERIC NOT NULL DEFAULT 0,
  engagement_dist_sum    NUMERIC NOT NULL DEFAULT 0,
  engagement_dist_count  INT     NOT NULL DEFAULT 0,
  first_blood_kills      INT     NOT NULL DEFAULT 0,
  first_blood_knocks     INT     NOT NULL DEFAULT 0,
  grenades_thrown        INT     NOT NULL DEFAULT 0,
  smokes_thrown          INT     NOT NULL DEFAULT 0,
  flashbangs_thrown      INT     NOT NULL DEFAULT 0,
  molotovs_thrown        INT     NOT NULL DEFAULT 0,
  grenade_damage         NUMERIC NOT NULL DEFAULT 0,
  molotov_damage         NUMERIC NOT NULL DEFAULT 0,
  grenade_hit_events     INT     NOT NULL DEFAULT 0,
  damage_taken           NUMERIC NOT NULL DEFAULT 0,
  blue_zone_damage       NUMERIC NOT NULL DEFAULT 0,
  heals_used             INT     NOT NULL DEFAULT 0,
  boosts_used            INT     NOT NULL DEFAULT 0,
  total_heal_amount      NUMERIC NOT NULL DEFAULT 0,
  revives                INT     NOT NULL DEFAULT 0,
  blue_zone_time         INT     NOT NULL DEFAULT 0,
  walk_distance          NUMERIC NOT NULL DEFAULT 0,
  ride_distance          NUMERIC NOT NULL DEFAULT 0,
  swim_distance          NUMERIC NOT NULL DEFAULT 0,
  vehicle_time           INT     NOT NULL DEFAULT 0,
  revives_given          INT     NOT NULL DEFAULT 0,
  assist_damage          NUMERIC NOT NULL DEFAULT 0,
  trade_kills            INT     NOT NULL DEFAULT 0,
  tradeable_deaths       INT     NOT NULL DEFAULT 0,
  zone_edge_samples      INT     NOT NULL DEFAULT 0,
  zone_total_samples     INT     NOT NULL DEFAULT 0,
  zone_outside_samples   INT     NOT NULL DEFAULT 0,
  zone_dist_sum          NUMERIC NOT NULL DEFAULT 0,
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stage_team_stats_stage ON stage_team_stats(stage_id);
ALTER TABLE stage_team_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stage_team_stats_public_read"   ON stage_team_stats;
DROP POLICY IF EXISTS "stage_team_stats_service_write" ON stage_team_stats;
CREATE POLICY "stage_team_stats_public_read"   ON stage_team_stats FOR SELECT USING (true);
CREATE POLICY "stage_team_stats_service_write" ON stage_team_stats FOR ALL    USING (auth.role() = 'service_role');

-- ── series_team_stats ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS series_team_stats (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  series_id              UUID NOT NULL REFERENCES series(id) ON DELETE CASCADE,
  team_id                UUID REFERENCES teams(id) ON DELETE SET NULL,
  team_name              TEXT NOT NULL,
  logo_url               TEXT,
  games                  INT     NOT NULL DEFAULT 0,
  wwcd                   INT     NOT NULL DEFAULT 0,
  kills                  INT     NOT NULL DEFAULT 0,
  assists                INT     NOT NULL DEFAULT 0,
  knocks                 INT     NOT NULL DEFAULT 0,
  headshot_kills         INT     NOT NULL DEFAULT 0,
  damage                 NUMERIC NOT NULL DEFAULT 0,
  survival_time          NUMERIC NOT NULL DEFAULT 0,
  deaths                 INT     NOT NULL DEFAULT 0,
  longest_kill           NUMERIC NOT NULL DEFAULT 0,
  knock_damage_sum       NUMERIC NOT NULL DEFAULT 0,
  engagement_dist_sum    NUMERIC NOT NULL DEFAULT 0,
  engagement_dist_count  INT     NOT NULL DEFAULT 0,
  first_blood_kills      INT     NOT NULL DEFAULT 0,
  first_blood_knocks     INT     NOT NULL DEFAULT 0,
  grenades_thrown        INT     NOT NULL DEFAULT 0,
  smokes_thrown          INT     NOT NULL DEFAULT 0,
  flashbangs_thrown      INT     NOT NULL DEFAULT 0,
  molotovs_thrown        INT     NOT NULL DEFAULT 0,
  grenade_damage         NUMERIC NOT NULL DEFAULT 0,
  molotov_damage         NUMERIC NOT NULL DEFAULT 0,
  grenade_hit_events     INT     NOT NULL DEFAULT 0,
  damage_taken           NUMERIC NOT NULL DEFAULT 0,
  blue_zone_damage       NUMERIC NOT NULL DEFAULT 0,
  heals_used             INT     NOT NULL DEFAULT 0,
  boosts_used            INT     NOT NULL DEFAULT 0,
  total_heal_amount      NUMERIC NOT NULL DEFAULT 0,
  revives                INT     NOT NULL DEFAULT 0,
  blue_zone_time         INT     NOT NULL DEFAULT 0,
  walk_distance          NUMERIC NOT NULL DEFAULT 0,
  ride_distance          NUMERIC NOT NULL DEFAULT 0,
  swim_distance          NUMERIC NOT NULL DEFAULT 0,
  vehicle_time           INT     NOT NULL DEFAULT 0,
  revives_given          INT     NOT NULL DEFAULT 0,
  assist_damage          NUMERIC NOT NULL DEFAULT 0,
  trade_kills            INT     NOT NULL DEFAULT 0,
  tradeable_deaths       INT     NOT NULL DEFAULT 0,
  zone_edge_samples      INT     NOT NULL DEFAULT 0,
  zone_total_samples     INT     NOT NULL DEFAULT 0,
  zone_outside_samples   INT     NOT NULL DEFAULT 0,
  zone_dist_sum          NUMERIC NOT NULL DEFAULT 0,
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_series_team_stats_series ON series_team_stats(series_id);
ALTER TABLE series_team_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "series_team_stats_public_read"   ON series_team_stats;
DROP POLICY IF EXISTS "series_team_stats_service_write" ON series_team_stats;
CREATE POLICY "series_team_stats_public_read"   ON series_team_stats FOR SELECT USING (true);
CREATE POLICY "series_team_stats_service_write" ON series_team_stats FOR ALL    USING (auth.role() = 'service_role');
